# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
#from main import MainApp,HomeScreen
from PyQt5.QtWidgets import QMainWindow , QApplication , QDialog
class Ui_loginPage(object):
    def setupUi(self, loginPage):
        loginPage.setObjectName("loginPage")
        loginPage.resize(400, 233)
        self.verticalLayoutWidget = QtWidgets.QWidget(loginPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 30, 271, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
    
        self.retranslateUi(loginPage)
        QtCore.QMetaObject.connectSlotsByName(loginPage)
   
        
        
    def retranslateUi(self, loginPage):
        _translate = QtCore.QCoreApplication.translate
        loginPage.setWindowTitle(_translate("loginPage", "Dialog"))
        self.label.setText(_translate("loginPage", "SIGN IN"))
        self.lineEdit.setPlaceholderText(_translate("loginPage", "Admin"))
        self.lineEdit_2.setPlaceholderText(_translate("loginPage", "Password"))
        self.pushButton.setText(_translate("loginPage", "Log In"))


